"use client";

import { useMemo, useState } from "react";
import { BarChart, Bar, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, ScatterChart, Scatter } from "recharts";
import { useStudy } from "@/lib/store";
import { formatReward, localDate } from "@/lib/utils";
import type { StudyUnit } from "@/lib/types";

type Period = "7" | "30" | "all";
const pct = (a:number,b:number)=>b?Math.round(a/b*100):0;

export default function AnalyticsPage(){
  const {data}=useStudy(); const [period,setPeriod]=useState<Period>("30");
  const units=useMemo(()=>{if(period==="all")return data.units; const cutoff=new Date();cutoff.setDate(cutoff.getDate()-Number(period)+1);const key=localDate(cutoff);return data.units.filter(u=>u.date>=key);},[data.units,period]);
  const completed=units.filter(u=>u.status==="completed"); const started=units.filter(u=>!!u.startedAt); const skipped=units.filter(u=>u.status==="skipped"); const paused=units.filter(u=>(u.pausedCount??0)>0);
  const daily=useMemo(()=>{const map=new Map<string,number>();completed.forEach(u=>map.set(u.date,(map.get(u.date)||0)+1));return [...map].sort().map(([date,count])=>({date:date.slice(5),count}));},[completed]);
  const category=groupCount(completed,"category");
  const difficulty=["Easy","Normal","Hard"].map(name=>{const all=units.filter(u=>u.difficulty===name);return{name,rate:pct(all.filter(u=>u.status==="completed").length,all.length),count:all.length}});
  const rewardEffect=data.rewards.map(r=>{const all=units.filter(u=>u.rewardId===r.id);return{id:r.id,name:r.name,label:formatReward(r),rate:pct(all.filter(u=>u.status==="completed").length,all.length),n:all.length}}).filter(x=>x.n>0).sort((a,b)=>b.rate-a.rate);
  const hourBuckets=[{name:"06–10",a:6,b:10},{name:"10–14",a:10,b:14},{name:"14–18",a:14,b:18},{name:"18–22",a:18,b:22},{name:"22–02",a:22,b:26}].map(x=>{const relevant=started.filter(u=>{let h=new Date(u.startedAt!).getHours();if(h<6)h+=24;return h>=x.a&&h<x.b});return{name:x.name,rate:pct(relevant.filter(u=>u.status==="completed").length,relevant.length),n:relevant.length}});
  const scatter=completed.filter(u=>u.actualMinutes).map(u=>({estimated:u.estimatedMinutes,actual:u.actualMinutes,title:u.title}));
  const lengthBuckets=[{name:"≤10 min",test:(u:StudyUnit)=>u.estimatedMinutes<=10},{name:"11–20",test:(u:StudyUnit)=>u.estimatedMinutes>10&&u.estimatedMinutes<=20},{name:"21–40",test:(u:StudyUnit)=>u.estimatedMinutes>20&&u.estimatedMinutes<=40},{name:"40+",test:(u:StudyUnit)=>u.estimatedMinutes>40}].map(b=>{const x=units.filter(b.test);return{name:b.name,rate:pct(x.filter(u=>u.status==="completed").length,x.length),n:x.length}});
  const avgActual=completed.filter(u=>u.actualMinutes).reduce((s,u)=>s+(u.actualMinutes||0),0)/(completed.filter(u=>u.actualMinutes).length||1);
  const used=data.transactions.filter(tx=>tx.type==="use" && (period==="all" || localDate(new Date(tx.createdAt))>=(()=>{const d=new Date();d.setDate(d.getDate()-Number(period)+1);return localDate(d)})())).reduce((m,tx)=>{const r=data.rewards.find(x=>x.id===tx.rewardId);if(!r)return m;m[r.type]=(m[r.type]||0)+tx.amount;return m;},{} as Record<string,number>);
  return <div className="page"><header className="page-head"><div><div className="eyebrow">ANALYTICS</div><h1>Outputs, friction, reward response</h1></div><div className="segmented">{(["7","30","all"] as Period[]).map(p=><button key={p} className={period===p?"active":""} onClick={()=>setPeriod(p)}>{p==="all"?"All":`${p} days`}</button>)}</div></header>
  <section className="metric-grid analytics-metrics"><div className="metric"><span>Units / day</span><strong>{(completed.length/Math.max(1,period==="all"?new Set(units.map(u=>u.date)).size:Number(period))).toFixed(1)}</strong></div><div className="metric"><span>Completion rate</span><strong>{pct(completed.length,units.length)}<em>%</em></strong></div><div className="metric"><span>Avg. actual time</span><strong>{Math.round(avgActual)}<em> min</em></strong></div><div className="metric"><span>Started → completed</span><strong>{pct(completed.filter(u=>u.startedAt).length,started.length)}<em>%</em></strong></div></section>
  <section className="chart-grid"><Chart title="Completed Units / day" data={daily} dataKey="count"/><Chart title="Completed Units by subject" data={category} dataKey="count"/><Chart title="Completion rate by difficulty" data={difficulty} dataKey="rate" suffix="%"/><Chart title="Completion rate by start time" data={hourBuckets} dataKey="rate" suffix="%"/></section>
  <section className="section-block"><div className="section-head"><div><div className="eyebrow">REWARD EFFECTIVENESS</div><h2>Association between assigned reward and completion</h2><p className="subtle">Descriptive association only; this is not causal inference.</p></div></div><div className="effect-list">{rewardEffect.length?rewardEffect.map(r=><div className="effect-row" key={r.id}><div><strong>{r.label}</strong><span>{r.n} Units</span></div><div className="rate-bar"><i style={{width:`${r.rate}%`}}></i></div><b>{r.rate}%</b></div>):<div className="empty-card">Complete or skip more Units to populate this view.</div>}</div></section>
  <section className="section-block"><div className="section-head"><div><div className="eyebrow">FRICTION ANALYSIS</div><h2>Where Units stop</h2></div></div><div className="funnel-grid"><div><span>Created → Started</span><strong>{pct(started.length,units.length)}%</strong></div><div><span>Started → Completed</span><strong>{pct(completed.filter(u=>u.startedAt).length,started.length)}%</strong></div><div><span>Skipped</span><strong>{pct(skipped.length,units.length)}%</strong></div><div><span>Paused</span><strong>{pct(paused.length,started.length)}%</strong></div></div><div className="chart-grid two"><Chart title="Completion by estimated length" data={lengthBuckets} dataKey="rate" suffix="%"/><Chart title="Completion by difficulty" data={difficulty} dataKey="rate" suffix="%"/></div></section>
  <section className="section-block"><div className="section-head"><div><div className="eyebrow">ESTIMATE ACCURACY</div><h2>Estimated vs actual minutes</h2></div></div><div className="chart-card"><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:10,right:15,bottom:10,left:0}}><CartesianGrid stroke="var(--line)"/><XAxis type="number" dataKey="estimated" name="Estimated" stroke="var(--muted)"/><YAxis type="number" dataKey="actual" name="Actual" stroke="var(--muted)"/><Tooltip cursor={{strokeDasharray:"3 3"}}/><Scatter data={scatter} fill="var(--accent)"/></ScatterChart></ResponsiveContainer></div></div></section>
  <section className="section-block"><div className="section-head"><div><div className="eyebrow">REWARD USAGE</div><h2>Used in selected period</h2></div></div><div className="metric-grid"><div className="metric"><span>Free Time used</span><strong>{Math.round(used.free_time||0)}<em> min</em></strong></div><div className="metric"><span>Money used</span><strong>¥{Math.round(used.money||0).toLocaleString()}</strong></div><div className="metric"><span>Custom uses</span><strong>{Math.round(used.custom||0)}</strong></div></div></section>
  </div>;
}

function groupCount(units:StudyUnit[],key:"category"){const m=new Map<string,number>();units.forEach(u=>m.set(u[key],(m.get(u[key])||0)+1));return [...m].map(([name,count])=>({name,count}));}
function Chart({title,data,dataKey,suffix=""}:{title:string;data:Array<Record<string,unknown>>;dataKey:string;suffix?:string}){return <div className="chart-card"><h3>{title}</h3><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{top:10,right:10,bottom:5,left:-20}}><CartesianGrid vertical={false} stroke="var(--line)"/><XAxis dataKey={(data[0]?.date?"date":"name") as string} stroke="var(--muted)" tickLine={false}/><YAxis stroke="var(--muted)" tickLine={false}/><Tooltip formatter={(v)=>[`${v}${suffix}`,title]}/><Bar dataKey={dataKey} fill="var(--accent)" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div>}
